### ISSUE TITLE
Add installation steps when running wiremock in docker

### ISSUE THREAD

**Issue by alexandre-chopin** [wiremock/wiremock-state-extension#11]
### Summary

Please provide a `docker run` command example with the `--extensions` flag for this specific extension.

### References

https://wiremock.org/docs/standalone/docker/#running-with-extensions

**Comment by dirkbolte** [comment]
Unfortunately, there's no docker image for 3.0.0-beta available yet - and the extension uses the new extension API. Will definitely add it once there is a docker image with 3.0.0-beta .

**Comment by dirkbolte** [comment]
merged
