### ISSUE TITLE
Full bodies have the quotes replaced with &quot; when being retrieved

### ISSUE THREAD

**Issue by nsfrias** [wiremock/wiremock-state-extension#115]
### Proposal

The retrieved response contains `&quot;` instead of `"` when a full body is stored with quotes.

```txt
{
	&quot;id&quot;: &quot;ec079c49-75aa-4864-aaf9-3931ff71f3a2&quot;,
	&quot;description&quot;: &quot;Somevalue&quot;,
	&quot;createdTs&quot;: &quot;2024-01-1610: 28: 30+0000&quot;
}
```

Note: I have not tried to record other state with quotes.

### Reproduction steps

This are my stubs:

```json
{
    "request": {
        "method": "POST",
        "urlPattern": "/example"
    },
    "response": {
        "status": 200,
        "bodyFileName": "body.txt" 
    },
    "serveEventListeners": [
        {
            "name": "recordState",
            "parameters": {
                "context": "{{jsonPath response.body '$.id'}}",
                "state": {
                    "fullBody": "{{jsonPath response.body '$'}}"
                }
            }
        }
    ]
}
```

```json
{
    "priority": 10,
    "request": {
        "method": "GET",
        "urlPattern": "/example/.+"
    },
    "response": {
        "status": 200,
        "headers": {
            "Content-Type": "application/json"
        },
        "body": "{{{state context=request.pathSegments.[1] property='fullBody'}}}"
    }
}
```

The body is stored in a separate file for clarity:

```txt
{
    "id": "{{randomValue type='UUID'}}",
    "description": "Some value",
    "createdTs": "{{now format='yyyy-MM-dd HH:mm:ssZ'}}"
}
```

I built the standalone jar locally using the code from version 0.6.1 .

I have send a tar.gz file that is ready to reproduce all you need to do is to:

```
tar -xvzf bug_report.tar.gz
cd bug_report
docker-compose up
curl -X POST http://localhost:11091/example

# copy the returned id and replace on the following GET

curl -X GET http://localhost:11091/example/id
```
[bug_report.tar.gz](https://github.com/wiremock/wiremock-state-extension/files/13948720/bug_report.tar.gz)

**Comment by dirkbolte** [comment]
will have a look.

**Comment by nsfrias** [comment]
Thank you for the prompt reply. 👍

**Comment by dirkbolte** [comment]
Was able to reproduce it but for me it turned out to be a documentation error: instead of `{{` in your eventListener, `{{{` is needed:

`"fullBody": "{{jsonPath response.body '$'}}"` -> `"fullBody": "{{{jsonPath response.body '$'}}}"`

The PR I created tested the behavior and updates the documentation. Can you check whether it works for you as well?

**Comment by nsfrias** [comment]
Thank you very much for your quick reply @dirkbolte
