### ISSUE TITLE
ClassCastException on using response templating

### ISSUE THREAD

**Issue by Aj-Patterson-KP** [wiremock/wiremock-state-extension#126]
### Proposal

Expected: Property returned as part of response body.

Actual Behavior: Response is defaulted to 500 error with body as below
> 1:46: java.lang.ClassCastException: class com.github.tomakehurst.wiremock.common.ListOrSingle cannot be cast to class java.lang.String (com.github.tomakehurst.wiremock.common.ListOrSingle is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')

### Reproduction steps

Request which initializes state:
```json
{
  "request": {
    "method": "POST",
    "urlPath": "/releasepoint/api/v6/NewRequest"
  },
  "response": {
    "status": 200,
    "jsonBody": {
      "WebOrderId": "{{ randomInt lower=1 upper=100000 }}",
      "RpNumber": "{{ randomInt lower=1 upper=100000 }}",
      "AuthoUploadStatus": "SUCCESS",
      "AuthoUploadFailMessage": null
    }
  },
  "serveEventListeners": [
    {
      "name": "recordState",
      "parameters": {
        "context": "{{ jsonPath response.body '$.RpNumber' }}",
        "state": {
          "Status": "In Process"
        }
      }
    }
  ]
}
```

Request which should return with accessed state:
```
{
  "request": {
    "method": "GET",
    "urlPath": "/releasepoint/api/v6/SearchRequest",
    "queryParameters": {
      "searchId": {
        "equalTo": "1"
      },
      "searchTerm": {
        "matches": "^[0-9]+$"
      }
    },
    "customMatcher": {
      "name": "state-matcher",
      "parameters": {
        "hasContext": "{{ request.query.searchTerm }}"
      }
    }
  },
  "response": {
    "status": 200,
    "jsonBody": {
      "TotalCount": 1,
      "Results": [
        {
          "RpNumber": "{{ request.query.searchTerm }}",
          "Status": "{{{ state context=request.query.searchTerm property='Status' }}}"
        }
      ]
    }
  }
}
```
Make a POST to the first endpoint and copy the returned "RpNumber" field. Then, make a GET request to the second endpoint with query parameters `searchId=1` and `searchTerm=<your-copied-RpNumber>`.

**Comment by dirkbolte** [comment]
Thx for the nice repro. Will have a look.

**Comment by dirkbolte** [comment]
can you check the version of  PR #127 whether it fixes the issue for you?

**Comment by Aj-Patterson-KP** [comment]
Sorry I'm not much of a Java user - have been working with the standalone jar, is there a built version I can quickly test with? It looks like it would work, from what I understand about the problem.

**Comment by dirkbolte** [comment]
Unfortunately no. Will upload one (will be tomorrow though).

**Comment by dirkbolte** [comment]
added artifact upload to the workflow. You can download the jars from https://github.com/wiremock/wiremock-state-extension/actions/runs/8658829827 .

**Comment by Aj-Patterson-KP** [comment]
Neither jar seems to register as an extension for me. I don't see any logs (in verbose mode) from Wiremock about a failed load, is there something about the build that would make it unrecognized?

**Comment by dirkbolte** [comment]
Shouldn’t. I will make a release then (0.6.3).

**Comment by Aj-Patterson-KP** [comment]
Unfortunately I'm still not seeing the extension load at all. Here's the docker-compose section I'm using:

```yaml
  http_mocks:
    image: 'wiremock/wiremock:latest'
    ports:
      - 8080:8080
    volumes:
      - ./src/Wiremock/files/:/home/wiremock/__files
      - ./src/Wiremock/mappings/:/home/wiremock/mappings
      - ./src/Wiremock/extensions/:/var/wiremock/extensions
    command: --verbose --global-response-templating --disable-gzip
```
files and mappings contains nothing interesting. extensions contains just the 0.6.3 standalone jar.

I did see this in the changelog, is that perhaps the cause?

> Bump org.wiremock.tools.gradle.wiremock-extension-convention from 0.1.2 to 0.2.0 (https://github.com/wiremock/wiremock-state-extension/pull/121)

**Comment by dirkbolte** [comment]
thx for the pointer. 0.6.4 is on its way.

**Comment by Aj-Patterson-KP** [comment]
Just tested with 0.6.4 and it worked like a charm. Thanks!!

**Comment by dirkbolte** [comment]
Thx for checking
