### ISSUE TITLE
Add 'default' parameter to the state handler

### ISSUE THREAD

**Issue by alexandre-chopin** [wiremock/wiremock-state-extension#18]
### Proposal

When retrieving the state, we often must check if the property is present in the state and otherwise generate a value for it.
This results in a lot of `contains ... 'ERROR'` checks, for example:

```
{{#assign 'environment'}}{{state context=request.pathSegments.[3] property='environment'}}{{/assign}}
{{#contains environment 'ERROR' }}{{#assign 'environment'}}{{pickRandom 'staging' 'production'}}{{/assign}}{{/contains}}
```

It would be nice to be able to specify a default value if the property is missing for the state. This would look like this:

```
{{#assign 'environment'}}{{state context=request.pathSegments.[3] property='environment' default=(pickRandom 'staging' 'production')}}{{/assign}}
```

This would be cleaner as well, because we wouldn't have to check for the specific error string which might change in the future AND we would avoid having errors being logged like:
`[ERROR: No state for context my_context, property environment found]`

**Comment by dirkbolte** [comment]
Nice idea. Will try to integrate it timely.

**Comment by dirkbolte** [comment]
See #19 as proposal. The PR is dependent on #17

**Comment by dirkbolte** [comment]
merged.
