### ISSUE TITLE
stop showing 'no state found' errors when a default value is specified

### ISSUE THREAD

**Issue by alexandre-chopin** [wiremock/wiremock-state-extension#25]
### Proposal

When specifying a value for the `default` property in the state template helper, we expect logs like `ERROR: No state for context my_context, property my_property found` not to show up or show up as an INFO level log because everything's fine.

**Comment by dirkbolte** [comment]
Would make it `INFO` then as it's a expected patch configured by the user.

**Comment by dirkbolte** [comment]
that was actually a bug. `Optional.orElse` should have been `Optional.orElseGet`

**Comment by dirkbolte** [comment]
merged
