### ISSUE TITLE
 Issue with State Handlebars Helper AbstractMethodError

### ISSUE THREAD

**Issue by ashuraits** [wiremock/wiremock-state-extension#36]
### Proposal

I'm encountering an issue while trying to utilize the State Handlebars Helper in WireMock. The error message I'm receiving is as follows:

`java.lang.AbstractMethodError: Receiver class org.wiremock.extensions.state.extensions.StateHandlerbarHelper does not define or inherit an implementation of the resolved method 'abstract java.lang.Object apply(java.lang.Object, wiremock.com.github.jknack.handlebars.Options)' of interface wiremock.com.github.jknack.handlebars.Helper.
`

### Reproduction steps

**Steps to Reproduce:**

Use Docker image wiremock/wiremock:3.x.
Map volumes for extensions.
Download the standalone JAR file from the releases page.

**Expected Behavior:**
I expected the State Handlebars Helper to work as intended without any errors.

Actual Behavior:
The error mentioned above is being encountered, preventing the S
tate Handlebars Helper from functioning correctly.

**Environment Details:**

Docker image: wiremock/wiremock:3.x
Volume mapping to extensions
Standalone JAR file downloaded from the releases page
Additional Information:
I'm seeking assistance in resolving this issue and getting the State Handlebars Helper to work without encountering the mentioned error. Any insights or guidance would be greatly appreciated.

**Comment by dirkbolte** [comment]
was able to reproduce it. Will look for a fix.

**Comment by dirkbolte** [comment]
should work now - the package relocation was wrong. Will create a new version soon, latest end of next week.

**Comment by zyberzebra** [comment]
I'm facing this problem with the newest Version.

**Comment by dirkbolte** [comment]
@zyberzebra can you open a new issue for it? Will look at it timely.

**Comment by zyberzebra** [comment]
@dirkbolte  
yes! 
Thanks for the quick answer!

I will open a new issue with a minimal reproducible setup as soon as I get to it!
