### ISSUE TITLE
Add README page to the demo

### ISSUE THREAD

**Issue by oleg-nenashev** [wiremock/wiremock-state-extension#63]
### Summary

It would be nice to have a README page that summarizes the demo in https://github.com/wiremock/wiremock-extension-state/tree/develop/demo/wiremock_state_extension_demo

The page would include:

- The general overview
- Link to the video: https://www.youtube.com/watch?v=OUrMEpzHbvY 
- Link to the slides: https://github.com/wiremock/wiremock-extension-state/blob/develop/demo/wiremock_state_extension_webinar.pdf 
- Steps how to run the demo locally (see the video)

Then this demo can be referenced from the main README page

**Comment by ayan-joshi** [comment]
I want to work on this issue , assign it to me @oleg-nenashev

**Comment by oleg-nenashev** [comment]
P.S: No need to assign, just submit a pull request

**Comment by ayan-joshi** [comment]
> P.S: No need to assign, just submit a pull request

okay sure @oleg-nenashev

**Comment by ayan-joshi** [comment]
@oleg-nenashev can you add hacktoberfest label ?

**Comment by oleg-nenashev** [comment]
> @oleg-nenashev can you add hacktoberfest label ?

No need. The entire repository is marked for Hacktoberfest.
Are you sure you're following the 2023 guidelines?

**Comment by ayan-joshi** [comment]
> > @oleg-nenashev can you add hacktoberfest label ?
> 
> No need. The entire repository is marked for Hacktoberfest. Are you sure you're following the 2023 guidelines?

ok ,Yes
