### ISSUE TITLE
Add more possible conditions to state-matcher

### ISSUE THREAD

**Issue by Tunduk** [wiremock/wiremock-state-extension#64]
### Proposal

So, we have the `hasNotProperty` and `hasNoProperty`. 
These only check if a key is present in context. 
It would be great to have something like "hasPropertyEqualTo" and "hasPropertyNotEqualTo".
To be honest I can't imagine use cases but why not?

**Comment by dirkbolte** [comment]
Might be used to simulate business logic (state changes). To go even further: maybe even allow generic Boolean logics to allow usage of handlebars #if . That won’t be pretty in the json but powerful.

**Comment by dirkbolte** [comment]
Small update: I’m trying to find a way to expose the built-in matchers of Wiremock. That provide much more flexibility.

**Comment by dirkbolte** [comment]
Found a way to expose pretty much all built-in matchers to both properties as well as list entries. PR is linked. Any feedback is welcome.

**Comment by Tunduk** [comment]
Looks awesome!

**Comment by dirkbolte** [comment]
merged
