### ISSUE TITLE
Log all contexts with values when verbose=true

### ISSUE THREAD

**Issue by Tunduk** [wiremock/wiremock-state-extension#65]
### Proposal

Sometimes it's hard to understand what is happening with context. Did I put the right value? Did I name the context right? 
It would be great to have a log for debugging purposes.

**Comment by dirkbolte** [comment]
Can you give some examples what would have been helpful?

**Comment by Tunduk** [comment]
When the `recordState` listener is executed - log "Context with name %context_name% with values $list_of_values% has been written"
When the `deleteState` listener is executed - log "Context with name %context_name% with values $list_of_values% has been deleted"
If we can hook to the handlebar helper `state` - log "Access to context %context-name% value %value_of_requested_property". 

I spent 30 minutes because I used a complex context name and added an extra underscore in the name =)

**Comment by dirkbolte** [comment]
Sorry to hear that and thanks for the examples.

**Comment by dirkbolte** [comment]
please check the PR #66 for a proposal on what and how things are logged. I would refrain from logging any values at these might contain data inserted by a user/tester.

**Comment by Tunduk** [comment]
Looks really good!
Thank you for your quick response and PR!
It will definitely help in my future work with the extension

**Comment by dirkbolte** [comment]
thx. Closing it then. Will publish a patch release in a jiffy. Happy coding!!
