### ISSUE TITLE
DeleteState context regex matching

### ISSUE THREAD

**Issue by dragutint** [wiremock/wiremock-state-extension#68]
### Proposal

It's possible to create context names based on input parameters and use them this way. 

When deleting contexts, you need to pass each context name for deletion. It'll be nice to have a feature of context name matching using regex. For example:

```
"serveEventListeners": [
		{
			"name": "deleteState",
			"parameters": {
				"context": "resource-xyz-.*"
			}
		}
	]
```

**Comment by dirkbolte** [comment]
should this delete all contexts matching the regex?

**Comment by dragutint** [comment]
> should this delete all contexts matching the regex?

Yes. 

e.g. two contexts
resourceXyz-uuid1
resourceXyz-uuid2

deleteState for `context "resourceXyz-.*"` will delete both contexts.

What do you think about this feature?

**Comment by dirkbolte** [comment]
sounds good. Was wondering whether it should be more explicit:

```json
"serveEventListeners": [
		{
			"name": "deleteState",
			"parameters": {
				"contextsMatching": "resource-xyz-.*"
			}
		}
	]
```

**Comment by dragutint** [comment]
> sounds good. Was wondering whether it should be more explicit:
> 
> ```json
> "serveEventListeners": [
> 		{
> 			"name": "deleteState",
> 			"parameters": {
> 				"contextsMatching": "resource-xyz-.*"
> 			}
> 		}
> 	]
> ```

Good, explicit approach! I like it.

**Comment by dirkbolte** [comment]
@dragutint can you check #98 (for the feature and also the code if you like)?

**Comment by dirkbolte** [comment]
PR is merged. In case you miss something of find a bug: feedback is very welcome.
